---
title: "Week 2 - Wednesday - Data Summaries and Visualization - Class Plan"
output:
  html_document: default
---

## Learning Objectives

* Describe and practice calculating various data summary statistics, including the mean, median, and measures of spread or variability.
* Identify differences between common summary statistics and know when to apply these metrics.
* Organize raw data into a frequency distribution using appropriate bin widths.
* Construct a histogram by hand based on a frequency table.
* Interpret the shape, center, and spread of a histogram in the context of a life science dataset (e.g., resting heart rates).
* Describe the distribution of a variable using appropriate statistical language (e.g., skewness, modality, outliers).


## Readings

* Vu, J. and Harrington, D. Introductory Statistics for the Life and Biomedical Sciences, First Edition. OpenIntro Project **Chapter 1 - Sections 4-7**

## Activities

* Wrap-up - CFS study design activity
* Resting Heart Rate - Data summary and histogram activity


