---
title: "Week 9 - Inference for Numerical Data - Power"
author: "Matthew E. Aiello-Lammens"
date: "10/19/2020"
output: 
  beamer_presentation:
    slide_level: 3
    toc: true
    fig_caption: false
---

# Statistical power and sample size

### Background

\small

Most studies are done to establish evidence in favor of an alternative hypothesis.

The **power** of a statistical test is the probability that the test will reject the null hypothesis when the alternative hypothesis is true.

  - In other words, power is the probability of correctly rejecting $H_0$.

Power depends on...

  - the hypothesized difference between two population means, also known as the population **effect size** ($|\mu_1 - \mu_2|$)
  
  - the population standard deviation of each group ($\sigma_1$, $\sigma_2$)
  
  - the sample size of each group ($n_1$, $n_2$)
  
Usually, a study team can only control sample size.


### Outcomes and errors in testing   

\begin{center}
\begin{tabular}{|l|l|l|} \hline
& \multicolumn{2}{c|}{\textbf{Result of test}} \\ \hline
\textbf{State of nature}  & \textbf{Reject $H_0$}  & \textbf{Fail to reject $H_0$}\\
\hline
 & Type I error, & No error,\\
$H_0$ is true & probability = $\alpha$ & probability = $1 - \alpha$ \\
 & (false positive) & (true negative) \\ \hline
 &  No error, & Type II error,\\
$H_A$ is true &  probability = $1 - \beta$ & probability = $\beta$\\
 & (true positive) & (false negative) \\ \hline
\end{tabular}
\end{center}   



### Error probabilities in testing  


  - Type I error is controlled via rejecting $H_0$ only when a $p$-value is smaller than $\alpha$.
  
  - Type II error (and power) is affected by sample size, standard deviation, and effect size.
  
      - As sample size increases, power increases.
      
      - As standard deviation decreases, power increases.
      
      - As effect size increases, power increases. 

### Choosing the right sample size

\small

Study design often includes calculating a study size (sample size) such that the probability of rejecting a null hypothesis is acceptably large, typically between 0.80 and 0.90. 

It is important to have a precise estimate of an appropriate study size.

  - A study needs to be large enough to allow for sufficient power to detect a difference between groups.
  
  - However, unnecessarily large studies are expensive, and can even be unethical.


### A typical sample size question

\small

A pharmaceutical company has developed a new drug to lower blood pressure and is planning a clinical trial to test its effectiveness.

  - Individuals whose systolic blood pressure is between 140 and 180 mmHg will be recruited.
  
  - Based on previous studies, blood pressures from such individuals will be approximately normally distributed with standard deviation of about 12 mmHg.
  
  - Participants will be randomly assigned to the new drug or a placebo, and the company will measure the difference in mean blood pressure levels between the groups.

The company expects to receive FDA approval for the drug if there is evidence that the drug lowers blood pressure, on average, by at least 3 mmHg more than the standard drug.

How large should the study be if the company wants the power of the study to be 0.80 (80%)?

### A typical sample size question \ldots

\small

*OI Biostat* Section 5.4 has an extended discussion of this example, with formulas for hand calculations.

Instead, we go right to the \textsf{R} function \texttt{power.t.test}. 

\scriptsize

```{r}
power.t.test(n = NULL, delta = 3, sd = 12, sig.level = 0.05, power = 0.80)
```




