---
title: "Meeting 4 - Data storage, pivot tables, and figures - Class Plan"
output:
  html_document: default
---

## Learning Objectives

* Be able to calculate basic summary statistics (mean and standard deviation) "by hand" and using a spread sheet program.
* Practice using Pivot tables in a spread sheet program.
* Describe how a histogram plot is a visual representation of the distribution of a set of data.
* Identify and describe the shape of a distribution of data.
* Be able to choose and identify a data visualization that is appropriate for a given set of data.

## Readings

* Vu, J. and Harrington, D. Introductory Statistics for the Life and Biomedical Sciences, First Edition. OpenIntro Project **Chapter 1 - Sections 4-7**

## Activities

1. Review
    * Mean
    * Median
    * Variance
    * Standard deviation
    * Shapes of distributions
2. Complete histogram worksheet
3. More about figures and data visualizations - slide deck 
4. Data storage best practices
    * Most data are collected as hard copies (handwritten) in the field or lab (i.e., in your lab notebook). We need to put these data into an electronic format for further analysis.
    * **EXERCISE** - Storing data electronically
        - With a partner, put the data from these linked data sheets into a Google Sheets file. [https://www.dropbox.com/s/hy1eu9wv8n1adtm/soil_p_data_collection.pdf?dl=0](https://www.dropbox.com/s/hy1eu9wv8n1adtm/soil_p_data_collection.pdf?dl=0)
    * **"Long" format** - In long format each row corresponds to one individual that was measured (or one case, to use our textbook terminology). Some information is redundant (e.g., site, date, vegetation type), but that this is necessary so that each row has all the important information about that individual case! Long format makes sorting easier, as well as enabling all sorts of analyses later on.
    * **Pivot tables** - One way to get many summary statistics at a time (and to do a whole lot of other things) is to use pivot tables. Pivot tables are available in most spread sheet programs (Google Sheets, Excel, etc.). They can be a bit complicated, and take some time to get used to, but once you do, they are quite powerful
        - Steps to your first pivot table
            1. Use the link to the Google Sheet provided in Classes. Make a copy of the data sheet for yourself.
            2. Go to “Insert” and choose “Pivot table …” - I prefer to have pivot tables as a new sheet, as this is cleaner. I encourage you to do the same. Note that there are some “Suggested” pivots you might do. Try the “Average of phosphorus_lbacre” option
            3. You can “Add” a new calculated "Values" - Choose “phosphorus_lbacre” again, and this time choose “Summarize by” as “STDEV”
            4. You can copy-paste your pivot table into another doc to make a nice data table for presentation
    * Figures in spread sheets (as time allows)